from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, RadioField, DateField

class userform(FlaskForm):
    EmployeeID = StringField('Employee ID')
    FirstName = StringField('First Name')
    MiddleName = StringField('Middle Name')
    LastName = StringField('Last Name')
    FatherName = StringField('Father Name')
    MotherName = StringField('Mother Name')
    DateOfBirth = DateField('Date Of Birth', format = '%d/%m/%Y')
    Gender = RadioField('Gender', choices = [('M','Male'),('F','Female'),('O','Other')])
    MaritialStatus = RadioField('Maritial Status', choices = [('M','Married'),('U','Unmarried'),('O','Other') ] )
    PermanentAddress = StringField('Permanent Address')
    LocalAddress = StringField('Local Address')
    EmailAddress = StringField('Email Address')
    ContactNumber1 = StringField('Contact Number 1')
    ContactNumber2 = StringField('Contact Number 2')
    FamilyPersonsName1 = StringField('Family Person Name 1')
    FamilyPersonsContactNumber1 = StringField('Family Persons Contact Number')
    FamilyPersonsRelationWithEmployee1 = StringField('Family Persons Relation With Employee')
    FamilyPersonsName2 = StringField('Family Person Name 2')
    FamilyPersonsContactNumber2 = StringField('Family Persons Contact Number 2')
    FamilyPersonsRelationWithEmployee2 = StringField('Family Persons Relation With Employee 2')
    AadharCard=StringField('Aadhar Card No')
    PanCard=StringField('Pan Card No')
    EductionalCourseDetail=StringField('Eductional Course Detail')
    PassingYear=StringField('Passing Year')
    PassingStatus=StringField('Passing Status')
    PFNomineeName=StringField('PF Nominee Name')
    PFNomineeRelation=StringField('PF Nominee Relation')
    PFNomineeDOB=StringField('PF Nominee DOB')
    DateOfJoining=StringField('Date Of Joining')
    DateOfResigning=StringField('Date Of Resigning')
    AccountNumber1 = StringField('Account Number 1')
    IFSCcode1 = StringField('IFSC Code')
    BankName1 = StringField('Bank Name')
    AccountType1 = StringField('Account Type')
    AccountHolderName1 = StringField('Account Holder Name')
    AccountNumber2 = StringField('Account Number 2')
    IFSCcode2 = StringField('IFSC Code')
    BankName2 = StringField('Bank Name')
    AccountType2 = StringField('Account Type')
    AccountHolderName2 = StringField('Account Holder Name')


###############################submit
    submit = SubmitField('Submit')
